sonar.projectKey=revision_cumplidos_proveedores_mf
sonar.projectName=revision_cumplidos_proveedores_mf
sonar.projectVersion=1.0

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
